### ISSUE TITLE
Very good, hope to do the same for the latest chatgpt page, support the author to keep updating

### ISSUE THREAD

**Issue by 6745060** [techwithanirudh/AnirudhGPT-for-Discourse#11]
Very good, hope to do the same for the latest chatgpt page, support the author to keep updating

**Comment by techwithanirudh** [comment]
Thanks! You are?

**Comment by 6745060** [comment]
> Thanks! You are?

Hello, I am from China, I developed your project in replit, you can leave a contact information, you can wechat or Twitter, Facebook, exchange and study

**Comment by techwithanirudh** [comment]
@6745060 Wdym? You are one of the developers of AnirudhGPT for Discourse, if so what's your replit username? 

This seems a lil :amongus:
